### ISSUE TITLE
Quick Motion Registration

### ISSUE THREAD

**Issue by Logiqx** [Logiqx/wsw-tech#23]
Require a process for quick allocation of new Motions.

**Comment by nickjpovey** [comment]
If we include allocation in the web process and that is the sole means of entry it will be taken care of when a new entrant signs up. I guess allocating a different unit due to loss or failure will be rare and could be a manual update in the SQL extract

**Comment by nickjpovey** [comment]
This can be done via the web site front end for end of day processing on a **per day basis**. The only exception will be in the event of a failed unit being replaced mid session, where provision to allow manual amendment of result processing files will be needed to enter multiple GPS units to one craft/person combination.

Need to be clear on the consequences to the results being generated in the event of units being re-allocated during the week and then the results from earlier days having to be re-run.

Hopefully the results processing takes note of the allocation of GPS ID along with the dates and times of applicability.

**Comment by Logiqx** [comment]
Closing this issue as we have a basic process for registering / allocating motions
