### ISSUE TITLE
Automatic entrant refresh

### ISSUE THREAD

**Issue by Logiqx** [Logiqx/wsw-tech#34]
Once new entrants are done by the website it would be good to have an automatic refresh.

Connect to the database over the internet, download the entrants, refresh the report.

**Comment by Logiqx** [comment]
After further thought, I wonder whether autmoation of this step is overkill.

A manual SQL extract prior to the daily results might be a better option.

Whilst automation would be handy and convenient it is one more thing that can potentially go wrong. Some examples:

- The results laptop would need to ensure that Docker has access to the local WiFi (WSW) and the internet. 
- There would be a dependency on WPNSA guest WiFi being operational and it allowing traffic on the MySQL port.
- Frequent splash screens from WPNSA Guest WiFi are liable to trip up an automated process.
- Opening up remote SQL access on the webserver should really be limited to specific IP ranges.
- Switching from WPNSA WiFi to mobile hotspot would necessitate changes in the remote access list.
- Switching from WPNSA WiFi to mobile hotspot may cause network complications for Docker.

Plus it's likely to be a few days of development time to create a reliable automated process.

I'm thinking a manual extract might be the way forward for 2023. Automation can always be considered for future years if the manual process feels too clunky during 2023.

**Comment by nickjpovey** [comment]
Solution implemented allows download of the most recent data via CSV file and web site front end. So could be done via cell phone if needs be. Access is via Joomla security using "SuperUser" accounts.

[WSW Entries (30).csv](https://github.com/Logiqx/wsw-tech/files/11305093/WSW.Entries.30.csv)

**Comment by Logiqx** [comment]
We now have a nice process for refreshing the entrant list:

1) Download CSV from the website
2) Run the Python script

Automation feels like overkill so we can refresh the list each day leading up to the event and each day during the event.
