### ISSUE TITLE
Limit results to 2 decimal places

### ISSUE THREAD

**Issue by Logiqx** [Logiqx/wsw-tech#37]
The GPS technology is not accurate to 3 decimal places.

Use 2 decimal places in all reports.

Note that internal logic using regular rounding. Need to consider whether floor() is more appropriate.

**Comment by nickjpovey** [comment]
Agreed

**Comment by Logiqx** [comment]
I have made the change. Results are rounded to the nearest 100th as per WSSRC records.

I reviewed the HTML changes using the following command:

```sh
find docs -name '*.html' -exec git diff {} \; | grep '^+'| grep -v '\.[0-9][0-9]<\/td>' | grep -v class.*medium | more
```

WSW results / rankings were unaffected which says we've never had a tie on the 100th of a knot.

UKWA results can sometimes be affected, after rounding runs to 2 decimal places then calculating the average.
