### ISSUE TITLE
Ensure correct Motion used with correct craft

### ISSUE THREAD

**Issue by nickjpovey** [Logiqx/wsw-tech#48]
For multi craft entrants there is a need to clearly mark units for craft type.

Could help find units if they all had craft type marked on them.

Manually label? Probably.

Labels could be pre-printed and applied as required. Different colour tapes?

**Comment by Logiqx** [comment]
I agree, manually attached labels and different colour tapes is a great idea.

Could even print craft icons if we're feeling fancy. :)

**Comment by nickjpovey** [comment]
https://www.amazon.co.uk/dp/B0BBLCKBMN/ref=sspa_dk_detail_0?pd_rd_i=B0BBLCKBMN

Cheap colour coding solution, I'll get two sets now.

**Comment by Logiqx** [comment]
Related to #53 - allocation of Motions

**Comment by Logiqx** [comment]
I think we have this sorted now - coloured labels, one says the craft and the other is the name tag.

Closing issue
