### ISSUE TITLE
SQL Push or Pull?

### ISSUE THREAD

**Issue by nickjpovey** [Logiqx/wsw-tech#49]
The WSW web site database will be the source for entrant data. 

What type of process will be needed to get this data for result processing?

Remote login to MySQL as a pre-cursor to result processing or a push process on the web site creating a csv file.

**Comment by Logiqx** [comment]
For simplicity during the event, I think a pull process would be cleanest.

It can either run regularly throughout the day or as a bare minimum, prior to results being done at the end of the day. 

Regardless of how the entrant + motion data is stored in the Joomla database, SQL views can be used to provide simplified access.

**Comment by Logiqx** [comment]
Related to #34 (Automatic Entrant Refresh)

My latest thinking is that a manual process is possibly the best idea for 2023. See #34 for my reasons.

**Comment by nickjpovey** [comment]
The solution I have implemented allows "SuperUser" access to frontend edit and data download from the web site.
