### ISSUE TITLE
Entrant Printed Information

### ISSUE THREAD

**Issue by nickjpovey** [Logiqx/wsw-tech#50]
We need to create a process to generate the info needed by the "office team" to administer entrants and produce individual printed sheets.

**Comment by Logiqx** [comment]
I can create some kind of Python process to do this task.

Initial thought is to generate PDF or Word documents that can be manually printed.

**Comment by nickjpovey** [comment]
[Competitor info sheet for office.docx](https://github.com/Logiqx/wsw-tech/files/9882643/Competitor.info.sheet.for.office.docx)

First draft of a simpler data form for the office I'll check with Norman and review how the sheets were used this year and if any other data would be beneficial.

Need to add chosen shirt size to the printout.

**Comment by nickjpovey** [comment]
Definitely manually printed. The bulk before leaving home, it would therefore be preferable if the sheets could be created via the web site? I'll investigate if any Joomla plugins exist for such a thing. 

Currently we generate an HTML email to the entrant with much of the data, perhaps this could be refined with us as recipient??

**Comment by nickjpovey** [comment]
Just a little pondering and I think the way forward is an HTML email that gets sent via the web on entry form submission. Currently I'm using the code below with the 'Fabrik' Joomla extension but I'm sure it would be possible to build into it a graphic header and a table to get it to format as required for printing. Some of the values are created 'on the fly' within the form via javascript or such like coding e.g. amount due.

Dear {reg_entrant___namedisplay},<br>

Thank you for your entry to Weymouth Speed Week 2023. We look forward to seeing you there.<br>


When paying by bank transfer please use this reference {reg_entrant___id}/{reg_person___id}.<br>

Our Bank details are:</p>Weymouth Speed Week for some banks we have been informed that the account name only matches on the abbrievation Weymouth SW (HSBC classes the account type as "Charitable")<br>
Sort Code:  403810<br>
Account Number:  01462288<br>
SWIFT or BIC:  HBUKGB4108V<br>
International Bank Account Number:  GB38HBUK40381001462288<br>
<br>
Thank you<br>

<hr>

<pThe details recorded for your entry are as follows:</p>
  
New Entrant: ID: {reg_entrant___id} - {reg_entrant___namedisplay}<br>
<br>

Email: {reg_entrant___emaildisplay}<br>
Entry for Event {reg_entrant___eventid}:<br>
Entry Type: {reg_entrant___entrytype}<br>
Status: {reg_entrant___calcstatus}<br>
Craft: {reg_entrant___crafttype}<br>
Sponsorship: {reg_entrant___sponsorship}<br>
Group: {reg_entrant___grouping}<br>
UKWA Member: {reg_entrant___ind_memberukwa}<br>
Boat Name: {reg_entrant___boatname}<br>
First Timer: {reg_entrant___calc_ind_firsttimer}<br>
Fees:<br>
Entry: {reg_entrant___entryfee}<br>
Rash Vest deposit: {reg_entrant___rashvestfee}<br>

<br>
Total Amount: {reg_entrant___totalamount}<br>

**Comment by Logiqx** [comment]
This sounds like a very good idea.

Having all entry-related activities done from the Joomla environment makes a lot of sense.

**Comment by nickjpovey** [comment]
[wsw-entry-1.pdf](https://github.com/Logiqx/wsw-tech/files/11305081/wsw-entry-1.pdf)
This is an example of the "office" entrant data produced as a PDF when the Motions have been allocated.

Job done.
