### ISSUE TITLE
Allocation of Motions

### ISSUE THREAD

**Issue by Logiqx** [Logiqx/wsw-tech#53]
We need a process to allocate Motions to people who are hiring.

After careful consideration, I think this is best placed in the Joomla environment / database. One of the big advantages of this is that the allocation of tallies and Motions can all be done prior to the event, without any dependency on the Python / Docker environment. Tally numbers are just the entrant number (typically 1 upwards). Motion IDs can be allocated to entrants once their entry has been reviewed and perhaps only once they have paid?

The Joomla database will therefore contain the list of entrants (including tally numbers) and a list of Motions assignments.

Notes:

- Entrants may need to be assigned a second Motion mid-week if their Motion is lost / broken / faulty.
- Motions may be re-allocated mid-week (e.g. Youth weekend units re-assigned to 2-day entries).

It may be that Motion assignment is a relatively manual process but it could be seeded by the initial entry.

**Comment by Logiqx** [comment]
This is also related to #23 (Quick Motion Registration) which will be handled by the Joomla environment.

**Comment by nickjpovey** [comment]
I believe we now have a solution. When you have a free hour or so try making an entry on the WSW web site as a competitor and then visit the "WSW Entries" menu option. There you will be able to edit each entry - e.g. allocate the Motion number(s), when that is saved a PDF is produced for the office with all the necessary data they need (including Tally number) and there is also an option to download the data you need as a CSV file. So all "admin" can be done via the web site frontend.

**Comment by Logiqx** [comment]
Related to #57 (allocating motions)

Happy with the Joomla solution so closing this issue
