### ISSUE TITLE
Allocating Motions

### ISSUE THREAD

**Issue by nickjpovey** [Logiqx/wsw-tech#57]
It would be nice to do this automatically, but it is complex to achieve and fraught with problems if people cancel or alter their entry.

A well ordered manual process may be the answer.

There are two types of entry - pre-event and on the day. It would be nice to use the same process for either.

My current proposal, which has been implemented, but is open for discussion,/modification/rejection is as follows:

As people enter we currently receive their details and the "office" sheet, I am hoping that I can "transfer" the Office sheet creation to a "The record has been edited" trigger........

If a SuperUser (currently Mike and Nick) logs on to the website they will see an additional menu item "This year's entries to Weymouth Speed Week". Clicking that will bring up a list of entries complete with an Edit option. Thus we can edit the Motion fields by inserting the serial number of the unit allocated. This page also allows the csv file to be downloaded.

So pre-event we can allocate units, and at the event we can get new entrants to complete their entry on-line and then, using our own laptop, allocate the Motions to them.

**Comment by nickjpovey** [comment]
Yay! So I now get an "Office sheet" when the record is edited.

**Comment by Logiqx** [comment]
Related to #53 (allocation of motions)

The Joomla process is working nicely for 2023 so closing this issue.

If we want to do automated allocations in the future, it can be a new issue
