### ISSUE TITLE
Motion Firmware - Charging Observations - Maintenance Task?

### ISSUE THREAD

**Issue by nickjpovey** [Logiqx/wsw-tech#60]
Thought I would see how the Motions are doing in storage and was surprised to find about half didn't have enough power to turn on. So my conclusion is that they do have some residual process that drains the power as Lithium cells are normally fantastic at holding charge. So perhaps we need to schedule a 3 or 4 monthly maintenance charge.

Also noted that on charging there are a few units that do not report their charge state via flashing LEDs every minute or so during charge. They must be a different firmware. So need to schedule a firmware update to a preferred common standard before October.

**Comment by nickjpovey** [comment]
Checked today - 5 weeks later and found 5 unresponsive and flat (615, 625, 630, 635 & 724) The 600's are charging 724 isn't taking a charge.....

The rest are bordering between 3 greens and 2 greens ~ 70%

When charged I'll see what firmware the 600 ones are. They were all in the original batch used at Weymouth.

**Comment by nickjpovey** [comment]
The 600s were firmware 9002 and the 724 eventually took charge and is 3187 Development.

**Comment by Logiqx** [comment]
9002 is the latest WSW custom firmware with our settings. Here are my notes of the 9xxx versions.

### Mini-Motion-9000 (2022-10-06)

First WSW release, presumably based on 3170.

Any Mini/LCD on firmware 9000 Weymouth:
- 5Hz
- 5kn min
- UTC+1
- WSW WiFi

Any Mini on firmware 9000 Weymouth:
- Blinker on

Minis that are WSW on firmware 9000 Weymouth (so far these are only 470, 619, 621, 633, 634):
- name WSW
- kn speed
- km distance
- 500m last, 500m best, 250m last, 250m best speed blinkers with 0 subtraction so 26kn = 2 red + 6 green blinks



### Mini-Motion-9001 (2022-10-06)

New list of devices:

> 601 611 615 617 618 619 621 625 630 631 632 633 634 635 639 656



### Mini-Motion-9002 (2022-10-07)

Correct WiFi password and edition/deletion forbidden.

**Comment by Logiqx** [comment]
I still need to do my bit about the device ID list...

**Comment by Logiqx** [comment]
Closing this issue as we now have a standard firmware on all devices and know to charge every 3 or 4 months.
